/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Branch: typeof import('./src/components/Branch.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    FamilyTree: typeof import('./src/components/FamilyTree.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
